require 'csv'    
require "#{Rails.root}/app/helpers/players_helper"
include PlayersHelper

namespace :db do
  desc "Transfiere a los jugadores"
   
  task assign_teams: :environment do
    t=Team.find(3)#ANTIGUA
    p=Player.find(62218)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59300)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60472)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64694)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61759)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58465)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60517)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59418)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62361)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58218)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61177)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57587)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62666)
    p.club=t.name
    p.team=t
    p.save
    
    t=Team.find(6)#BAZINGA
    p=Player.find(58289)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62944)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57841)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61601)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57044)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61048)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61396)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59997)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62045)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57035)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60298)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58358)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57270)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59466)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58575)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(65210)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57387)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61275)
    p.club=t.name
    p.team=t
    p.save
    

    t=Team.find(15)#COLORADO 36
    p=Player.find(59643)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60034)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64054)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62587)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59025)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60812)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60162)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64058)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62728)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59473)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64146)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59955)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63586)
    p.club=t.name
    p.team=t
    p.save

    t=Team.find(4)#CSP
    p=Player.find(63974)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57230)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63934)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63091)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59599)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59397)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57493)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(65478)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58085)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(65105)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59759)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61093)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63212)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63552)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(56919)
    p.club=t.name
    p.team=t
    p.save
    
    
    t=Team.find(14)#DEFENSORES
    p=Player.find(64466)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(56961)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58579)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60157)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62870)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59362)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61004)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57717)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57425)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60613)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58047)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59319)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63599)
    p.club=t.name
    p.team=t
    p.save
  
    t=Team.find(13)#GREEN MACHINE
    p=Player.find(59551)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58509)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57654)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57206)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63776)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62337)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57773)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59460)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60342)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(65115)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64124)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64318)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57414)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60618)
    p.club=t.name
    p.team=t
    p.save
    

    t=Team.find(5)#HONOLULU LIGHTS
    p=Player.find(62658)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61002)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64411)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57199)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57943)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64067)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61255)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57224)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63257)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(65453)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57593)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61425)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63318)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61203)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63480)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57326)
    p.club=t.name
    p.team=t
    p.save
 

    t=Team.find(8)#SAINT BASTIAN
    p=Player.find(60663)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58766)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(56979)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58667)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64619)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60711)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64873)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62539)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62572)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60732)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64386)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61830)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57169)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64872)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61332)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63491)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59725)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58294)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62837)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(56798)
    p.club=t.name
    p.team=t
    p.save
    

    t=Team.find(9)#SPORTIVO FIESTA
    p=Player.find(61598)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57551)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61545)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59129)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61833)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(56854)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63576)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63713)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(56893)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61174)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58682)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58755)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64218)
    p.club=t.name
    p.team=t
    p.save
    

    t=Team.find(7)#USPALLATA
    p=Player.find(65102)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59138)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62902)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60722)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63510)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59742)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61659)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57360)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57554)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64579)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57480)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60607)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64311)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61460)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59691)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58173)
    p.club=t.name
    p.team=t
    p.save

    t=Team.find(10)#WISCONSIN
    p=Player.find(62035)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62346)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(58526)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63401)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(62235)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(64363)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59302)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(65097)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63569)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57205)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59247)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(60148)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59756)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59558)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(57107)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(63385)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59825)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59752)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(61923)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59915)
    p.club=t.name
    p.team=t
    p.save
    p=Player.find(59917)
    p.club=t.name
    p.team=t
    p.save
   
   
  end
end