class AddIndexPlayers < ActiveRecord::Migration
  def change
    add_index :players, :name
    add_index :players, :nationality
    add_index :players, :club
    add_index :players, :registeredPosition
    add_index :players, :age
    add_index :players, :overallRating
    add_index :players, :techniqueRating
    add_index :players, :speedRating
    add_index :players, :physicalRating
    add_index :players, :resistanceRating
    add_index :players, :attack
    add_index :players, :defence
    add_index :players, :headerAccuracy
    add_index :players, :dribbleAccuracy
    add_index :players, :shortPassAccuracy
    add_index :players, :shortPassSpeed
    add_index :players, :longPassAccuracy
    add_index :players, :longPassSpeed
    add_index :players, :shotAccuracy
    add_index :players, :placeKicking
    add_index :players, :swerve
    add_index :players, :ballControl
    add_index :players, :goalKeepingSkills
    add_index :players, :response
    add_index :players, :explosivePower
    add_index :players, :dribbleSpeed
    add_index :players, :topSpeed
    add_index :players, :bodyBalance
    add_index :players, :stamina
    add_index :players, :kickingPower
    add_index :players, :jump
    add_index :players, :tenacity
    add_index :players, :teamwork
    add_index :players, :form
    add_index :players, :weakFootAccuracy
    add_index :players, :weakFootFrequency
    add_index :players, :attackAwareness
    add_index :players, :defenceAwareness
    add_index :players, :gk
    add_index :players, :swp
    add_index :players, :cb
    add_index :players, :rb
    add_index :players, :lb
    add_index :players, :dmf
    add_index :players, :cmf
    add_index :players, :rmf
    add_index :players, :lmf
    add_index :players, :amf
    add_index :players, :rwf
    add_index :players, :lwf
    add_index :players, :ss
    add_index :players, :cf
    add_index :players, :strongerFoot
    add_index :players, :injuryTolerance
    add_index :players, :s01OneTouchPlay
    add_index :players, :s02OutsideCurve
    add_index :players, :s03LongThrow
    add_index :players, :s04SuperSub
    add_index :players, :s05SpeedMerchant
    add_index :players, :s06LongRangeDrive
    add_index :players, :s07ShoulderFeintSkills
    add_index :players, :s08TurningSkills
    add_index :players, :s09RouletteSkills
    add_index :players, :s10FlipFlapSkills
    add_index :players, :s11FlickingSkills
    add_index :players, :s12ScissorsSkills
    add_index :players, :s13StepOnSkills
    add_index :players, :s14SideSteppingSkills
    add_index :players, :p01ClassicNo10
    add_index :players, :p02AnchorMan
    add_index :players, :p03Trickster
    add_index :players, :p04DartingRun
    add_index :players, :p05MazingRun
    add_index :players, :p06PinpointPass
    add_index :players, :p07EarlyCross
    add_index :players, :p08BoxToBox
    add_index :players, :p09IncisiveRun
    add_index :players, :p10LongRanger
    add_index :players, :p11Enforcer
    add_index :players, :p12GoalPoacher
    add_index :players, :p13DummyRunner
    add_index :players, :p14FreeRoaming
    add_index :players, :p15TailsMan
    add_index :players, :p16FoxInTheBox
    add_index :players, :p17OffensiveSideback
    add_index :players, :p18TrackBack
  end
end
