class CreatePlayers < ActiveRecord::Migration
  def change
    create_table :players do |t|
      t.integer :pesPlayerId
      t.string :name
      t.string :nationality
      t.string :club
      t.string :registeredPosition
      t.integer :age
      t.integer :overallRating
      t.string :techniqueRating
      t.string :speedRating
      t.string :physicalRating
      t.string :resistanceRating
      t.integer :attack
      t.integer :defence
      t.integer :headerAccuracy
      t.integer :dribbleAccuracy
      t.integer :shortPassAccuracy
      t.integer :shortPassSpeed
      t.integer :longPassAccuracy
      t.integer :longPassSpeed
      t.integer :shotAccuracy
      t.integer :placeKicking
      t.integer :swerve
      t.integer :ballControl
      t.integer :goalKeepingSkills
      t.integer :response
      t.integer :explosivePower
      t.integer :dribbleSpeed
      t.integer :topSpeed
      t.integer :bodyBalance
      t.integer :stamina
      t.integer :kickingPower
      t.integer :jump
      t.integer :tenacity
      t.integer :teamwork
      t.integer :form
      t.integer :weakFootAccuracy
      t.integer :weakFootFrequency
      t.integer :attackAwareness
      t.integer :defenceAwareness
      t.boolean :gk
      t.boolean :swp
      t.boolean :cb
      t.boolean :rb
      t.boolean :lb
      t.boolean :dmf
      t.boolean :cmf
      t.boolean :rmf
      t.boolean :lmf
      t.boolean :amf
      t.boolean :rwf
      t.boolean :lwf
      t.boolean :ss
      t.boolean :cf
      t.string :strongerFoot
      t.string :injuryTolerance
      t.boolean :s01OneTouchPlay
      t.boolean :s02OutsideCurve
      t.boolean :s03LongThrow
      t.boolean :s04SuperSub
      t.boolean :s05SpeedMerchant
      t.boolean :s06LongRangeDrive
      t.boolean :s07ShoulderFeintSkills
      t.boolean :s08TurningSkills
      t.boolean :s09RouletteSkills
      t.boolean :s10FlipFlapSkills
      t.boolean :s11FlickingSkills
      t.boolean :s12ScissorsSkills
      t.boolean :s13StepOnSkills
      t.boolean :s14SideSteppingSkills
      t.boolean :p01ClassicNo10
      t.boolean :p02AnchorMan
      t.boolean :p03Trickster
      t.boolean :p04DartingRun
      t.boolean :p05MazingRun
      t.boolean :p06PinpointPass
      t.boolean :p07EarlyCross
      t.boolean :p08BoxToBox
      t.boolean :p09IncisiveRun
      t.boolean :p10LongRanger
      t.boolean :p11Enforcer
      t.boolean :p12GoalPoacher
      t.boolean :p13DummyRunner
      t.boolean :p14FreeRoaming
      t.boolean :p15TailsMan
      t.boolean :p16FoxInTheBox
      t.boolean :p17OffensiveSideback
      t.boolean :p18TrackBack
      
      t.timestamps
    end
  end
end
